name: gateway-service

on:
  push:
    branches: [ master ]
    paths:
      - 'gateway-service/**'
env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_NAME: myapp
  TAG: ${{ github.sha }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Build with Maven
        run: mvn clean package
      
      - name: Login to Azure
        uses:  Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Configure Docker
        uses:  docker/login-action@v3.3.0
      
      - name: Build and push image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: |
            ${AZURE_CONTAINER_REGISTRY}/${IMAGE_NAME}:${TAG}
            ${AZURE_CONTAINER_REGISTRY}/${IMAGE_NAME}:latest
      
      - name: Update latest tag
        run: |
          az acr repository show-tags --name ${AZURE_CONTAINER_REGISTRY} --repository ${IMAGE_NAME} --output tsv | grep -v latest | head -n 1 | xargs -I {} az acr repository delete --name ${AZURE_CONTAINER_REGISTRY} --image ${IMAGE_NAME}:{} --yes
